name: Build

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "default.nix"
      - "app/**"
      - "nix/**"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "default.nix"
      - "app/**"
      - "nix/**"

jobs:
  build:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v10
        with:
          name: moergo-glove80-zmk-dev
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build Glove80 combined firmware
        run: nix-build -A glove80_combined -o combined
      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 glove80.uf2
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: glove80.uf2
          path: glove80.uf2
